# Generated by Django 3.0.3 on 2020-06-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=8)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('confirmed', models.FloatField(null=True)),
                ('recovered', models.FloatField(null=True)),
                ('deaths', models.FloatField(null=True)),
            ],
        ),
    ]
